partitions:
  small:
    - "spotshort"
  large:
    - "hpc"

tmpdir: "temp"

default:
  threads: 1
  memory: 2000
  partition: "small"

bcftools:
  threads: 1
  memory: 2000
  partition: "small"

happy:
  threads: 4
  memory: 16000
  partition: "large"

r:
  threads: 1
  memory: 3500
  partition: "small"

rtg-vcfeval:
  threads: 1
  memory: 16000
  partition: "large"

svanalyzer:
  threads: 1
  memory: 8000
  partition: "large"

svdb:
  threads: 1
  memory: 8000
  partition: "large"

truvari:
  threads: 1
  memory: 24000
  partition: "large"
